#!/usr/bin/env python


import argparse
import time


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('start_time_file')
    parser.add_argument('run_time_file')
    return parser.parse_args()

def main():
    args = parse_args()
    data = open(args.start_time_file).read().strip()
    start_time = float(data)
    run_time = time.time() - start_time
    with open(args.run_time_file, 'w') as f:
        f.write('%s\n' % run_time)

if __name__ == '__main__':
    main()
